---
title: "6414_project"
author: "Mark Luo"
date: "11/19/2019"
output: html_document
---

```{r}
data <- read.csv("reg_data.csv")
sqdata <- data[-c(2, 5, 13)]
countries <- sqdata[1]
sqdata <- sqdata[-1]
sqdata
# summary(sqdata)
```



```{r}

model_suicidelm <- lm(sqrt_suicides~., data=sqdata)
summary(model_suicidelm)
```

The effect of gini is statistically significant on suicide rate. more equality (lower gini) correlated with less suicides
population is not statistically significant.

```{r}
library(car)
vif(model_suicidelm)
1/(1-summary(model_suicidelm)$r.squared)
```



```{r}
library(glmnet)
response <- data$sqrt_suicides
predictors <- model.matrix(sqrt_suicides ~ ., data = sqdata)
```



```{r}
# Lasso
set.seed(0)
lambda = seq(0.01, 1, by=0.01)
suicide_model.cv=cv.glmnet(predictors,response,alpha=1,nfolds=10)
suicide_model = glmnet(predictors, response, alpha = 1, nlambda = 100,lambda=lambda)
coef(suicide_model,s=suicide_model.cv$lambda.min)
plot(suicide_model,xvar="lambda",lwd=1)
abline(v=log(suicide_model.cv$lambda.min),col='black',lty = 2,lwd=1)
```



```{r}
# Elastic Net
set.seed(100)
suicide_model.cv=cv.glmnet(predictors,response,alpha=0.5,nfolds=10)
suicide_model = glmnet(predictors,response, alpha = 0.5, nlambda = 100)
coef(suicide_model,s=suicide_model.cv$lambda.min)
plot(suicide_model,xvar="lambda",lwd=1)
abline(v=log(suicide_model.cv$lambda.min),col='black',lty = 2,lwd=1)

```


```{r}
minmod=lm(sqrt_suicides~1,data=data)
model_forward=step(minmod, scope = list(lower=minmod,upper=model_suicidelm), direction = "forward", trace=F)
summary(model_forward)
```


```{r}
model_backward=step(model_suicidelm, scope = list(lower=minmod,upper=model_suicidelm), direction = "backward", trace=F)
summary(model_backward)
```

```{r}
colnames(sqdata)
```

```{r}
table = data.frame()
table[seq(1,8),1] = c(' ', ' ', ' ', ' ', 'x', 'x', ' ', 'x')
table[seq(1,8),2] = c(' ', ' ', ' ', ' ', 'x', 'x', ' ', 'x')
table[seq(1,8),3] = c(' ', ' ', ' ', ' ', 'x', ' ', ' ', ' ')
table[seq(1,8),4] = c(' ', ' ', 'x', ' ', 'x', ' ', ' ', ' ')
colnames(table) = c('Backward step', 'Forward step', 'Lasso', 'Elastic Net')
rownames(table) = c( "gdp_per_cap_usd", "population", "gini", "HDI", "median_age", "life_expectancy", "household_debt_percent_GDP", "happiness")
table
```






```{r}
suicidelm_enet <- lm(sqrt_suicides ~ gini + median_age, data=sqdata)
summary(suicidelm_enet)
```



```{r}
par(mfrow =c(2,2))
resids = rstandard(suicidelm_enet)
fits = suicidelm_enet$fitted
plot(fits, resids, xlab="Fitted Values", ylab="Residuals", main="Scatterplot")
abline(0,0)
qqnorm(resids, ylab="Standardized Residuals",
xlab="Normal Scores", main="QQ plot")
qqline(resids)
hist(resids, xlab="Residuals", main = "Histogram")

cook = cooks.distance(suicidelm_enet)
plot(cook, type="h", lwd=3, col="red", ylab = "Cook's Distance", main="Cook's Distance")
abline(4/50,0)

```






```{r}
par(mfrow =c(2,2))
resids2 = rstandard(model_backward)
fits = model_backward$fitted
plot(fits, resids2, xlab="Fitted Values", ylab="Residuals", main="Scatterplot")
abline(0,0)
qqnorm(resids2, ylab="Standardized Residuals", xlab="Normal Scores", main="QQ plot")
qqline(resids2)
hist(resids2, xlab="Residuals", main = "Histogram")

cook = cooks.distance(model_backward)
plot(cook, type="h", lwd=3, col="red", ylab = "Cook's Distance", main="Cook's Distance")
abline(4/50,0)
```



```{r}
# Poisson model
glmdata <- data[-c(1,2,5,12)]
suicide_poisson  = glm(suicide_no ~ gdp_per_cap_usd + gini+ HDI+median_age+life_expectancy+household_debt_percent_GDP+happiness + offset(log(population)), family = "poisson", data = glmdata)
summary(suicide_poisson)
```




```{r}
# GOF test Poisson
1-pchisq(suicide_poisson$deviance,suicide_poisson$df.residual)
#with Pearson residuals
pResid <- resid(suicide_poisson, type = "pearson")
1-pchisq(sum(pResid^2),suicide_poisson$df.residual)
```

```{r}
res = resid(suicide_poisson,type="deviance")
par(mfrow=c(1,2))
qqnorm(res, ylab="Std residuals")
qqline(res,col="blue",lwd=2)
hist(res,xlab="Std residuals", main="")
```











```{r}
poisson_base <- glm(suicide_no ~ 1 + offset(log(population)), family = "poisson", data = glmdata)
poisson_backward <- step(suicide_poisson, scope = list(lower=poisson_base,upper=suicide_poisson), direction = "backward", trace=F)
summary(poisson_backward)
```

```{r}
poisson_forward <- step(poisson_base, scope = list(lower=poisson_base,upper=suicide_poisson), direction = "forward", trace=F)
summary(poisson_forward)

```

```{r}
# Overdispersion
suicide_poisson$deviance/suicide_poisson$df.res

```


```{r}
# Quasifamily
suicide_poisson_quasi  = glm(suicide_no ~ gdp_per_cap_usd + gini+ HDI+median_age+life_expectancy+household_debt_percent_GDP+happiness + offset(log(population)), family = quasipoisson, data = glmdata)
summary(suicide_poisson_quasi)
```




```{r}
# Negative Binomial
library(MASS)
nb <- glm.nb(glmdata$suicide_no ~ glmdata$gdp_per_cap_usd + glmdata$gini+ glmdata$HDI+glmdata$median_age+glmdata$life_expectancy+glmdata$household_debt_percent_GDP+glmdata$happiness, data=glmdata)
summary(nb)
```






